ccflags-y := -Ofast -fgcse-las -fpredictive-commoning \
	     -ffast-math -fgcse-lm -fgcse-sm -fsched-spec-load \
	     -fforce-addr -fsingle-precision-constant -mcpu=cortex-a9 \
	     -mtune=cortex-a9 -marm -mfpu=neon-vfpv4 -fgraphite -fgraphite-identity \
	     -floop-flatten -floop-parallelize-all -ftree-loop-linear \
	     -floop-interchange -floop-strip-mine -floop-block

obj-y += msm_ion.o ion_cp_common.o
